In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt

In [59]:
dataset=pd.read_csv("E:\\Social_Advertisement_ds.csv")

In [60]:
dataset


User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018  Female   36            33000          0

[399 rows x 5 columns]

In [61]:
x=dataset.iloc[:,[2,3]].values

In [62]:
y=dataset.iloc[:,4].values

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [65]:
x_test


array([[    36,  33000],
       [    32,  86000],
       [    37,  53000],
       [    41,  59000],
       [    27,  90000],
       [    30,  62000],
       [    33,  31000],
       [    27,  54000],
       [    49,  39000],
       [    28,  79000],
       [    38,  80000],
       [    27,  96000],
       [    33,  60000],
       [    43, 129000],
       [    37,  78000],
       [    38, 113000],
       [    31,  74000],
       [    42, 108000],
       [    46,  22000],
       [    34,  43000],
       [    31,  71000],
       [    37,  70000],
       [    32, 117000],
       [    41,  51000],
       [    18,  68000],
       [    42,  80000],
       [    43, 133000],
       [    26,  35000],
       [    35,  22000],
       [    52,  90000],
       [    57,  60000],
       [    52, 114000],
       [    41,  71000],
       [    43, 112000],
       [    44, 139000],
       [    48, 141000],
       [    24,  32000],
       [    36, 125000],
       [    19,  70000],
       [    53,  34000],


In [66]:
x_train.shape


(299, 2)

In [67]:
y_train.shape


(299,)

In [68]:
from sklearn.preprocessing import StandardScaler

In [69]:
sc=StandardScaler()

In [70]:

x_train=sc.fit_transform(x_train)

In [71]:
x_test=sc.transform(x_test)

In [42]:
x_train

array([[ 1.48983898, -1.10972431],
       [-1.02689467, -1.20007765],
       [-0.15571763,  1.42016911],
       [-0.83329977, -1.29043098],
       [-1.12369211,  0.27569351],
       [ 1.58663643,  1.11899132],
       [ 0.23147216, -0.4170154 ],
       [-1.80127425, -1.38078432],
       [ 0.32826961,  0.03475128],
       [-0.25251508,  0.78769575],
       [-1.31728701, -1.56149099],
       [ 0.13467471,  0.0046335 ],
       [ 0.13467471,  0.24557573],
       [-1.60767935,  0.51663574],
       [-0.73650232,  1.93217134],
       [ 1.48983898,  2.17311357],
       [ 0.90905429,  2.20323135],
       [-0.05892019,  0.27569351],
       [ 0.90905429,  1.26958021],
       [-0.54290743,  0.45640019],
       [-0.73650232,  0.54675352],
       [-0.34931253, -0.8386643 ],
       [ 0.23147216, -0.35677984],
       [-0.25251508, -0.35677984],
       [ 0.42506705,  0.9985202 ],
       [ 2.07062367, -1.2603132 ],
       [ 2.16742112, -0.74831096],
       [-0.05892019, -0.56760429],
       [-1.02689467,

In [19]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
classifier=KNeighborsClassifier(n_neighbors=5,metric="minkowski")
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [44]:
y_predict=classifier.predict(x_test)

In [45]:
y_predict

array([0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [46]:
y_test

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [47]:
from sklearn.metrics import confusion_matrix

In [48]:
cm=confusion_matrix(y_predict,y_test)

In [57]:
cm

array([[58,  3],
       [ 8, 31]], dtype=int64)